### ISSUE TITLE
Implement bidirectional routing

### ISSUE THREAD

**Issue by dryewo** [zalando-stups/friboo#94]
Sometimes it's necessary to generate a resource URL from a handler function, for example, to provide "location" header. Concatenating strings is not an ideal solution. We can possibly support it by using vendor extension parameter in the spec:

```
  '/hello/{name}':
    x-path-id: hello-name
    get:
      summary: Gets hello
```

After this it should be possible to call a function to create a URL:

```
(path-for (:swagger request) :hello-name "Michael")
```

Challenges:
- need to support path parameters for routes
- need to patch [swagger1st](https://github.com/sarnowski/swagger1st) to allow vendor extensions on this level
- `(:swagger request)` - is it the best way to access the routing information?

Good existing solution: https://github.com/juxt/bidi
